AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Incident Management API - Serverless Backend

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        INCIDENTS_TABLE: !Ref IncidentsTable

Resources:
  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Incidents
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  IncidentApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: IncidentApi
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  IncidentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/incident/
      Handler: app.handler
      Events:
        GetIncidents:
          Type: Api
          Properties:
            RestApiId: !Ref IncidentApi
            Path: /incidents
            Method: get
        PostIncident:
          Type: Api
          Properties:
            RestApiId: !Ref IncidentApi
            Path: /incidents
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:Scan
              Resource: !GetAtt IncidentsTable.Arn

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${IncidentApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/incidents"

  IncidentsTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref IncidentsTable
